# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0004_mimianshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mimianshop',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
